package wallet

import (
	"testing"

	"github.com/nickmeessen/dag-go/tx"
	"github.com/stretchr/testify/suite"
)

type WalletTestSuite struct {
	suite.Suite
}

func TestWalletTestSuite(t *testing.T) {
	suite.Run(t, new(WalletTestSuite))
}

func (s *WalletTestSuite) TestNew() {
	s.Run("Create a new wallet successfully", func() {
		wallet, err := New()
		s.NoError(err)
		s.NotNil(wallet)
		s.NotEmpty(wallet.Address())
		s.NotEmpty(wallet.PeerID())
	})
}

func (s *WalletTestSuite) TestFromPrivateKey() {
	s.Run("Create a wallet from private key successfully", func() {
		wallet, err := FromPrivateKey("9bfe101efc5458ce1dfb8d56c91ad38effb6974d371b6ad206e484e49ed7013c")
		s.NoError(err)
		s.NotNil(wallet)
		s.Equal("DAG3jifKUZPc213rRLSfZVSLZfPRfX7fwTGh8tsy", wallet.Address())
		s.Equal("043a1d350d041e8291ce672386f80cabfc16716f5a54532e17519a66fe6f9fedd8717e327ff4be399a303a8de1056f4769750487a278b8f8fe4f7add55bd5b4d", wallet.PeerID())

		wallet, err = FromPrivateKey("6eb41c0be9ab83a61b954183dd14278c60c189a9e3de3570ff996d4c8043af6b")
		s.NoError(err)
		s.NotNil(wallet)
		s.Equal("DAG58AYZbPHyiYQcmD96T3zWK2HyN3Zc3cjWGqi7", wallet.Address())
		s.Equal("648e3c3c885e8c8077fcc3dc4b1990bae2c30562aded1fdc1c689ef7c9adbaee709cd9a1f7a914268f768b310dde7f0cedc2e2c39ffafa31f56819cb8435ba98", wallet.PeerID())
	})
}

// TestSign cross-validates the signing chain against a known-answer vector
// generated by dag4.js. The transfer inputs and fixed salt were run through
// dag4.keyStore.prepareTx + dag4.keyStore.sign; the expected signature below
// is the exact DER-encoded hex that dag4.js produced. A match proves Go
// output is byte-for-byte protocol-compatible with the JS reference.
func (s *WalletTestSuite) TestSign() {
	s.Run("byte-matches dag4.js vector with fixed salt", func() {
		w, err := FromPrivateKey("9bfe101efc5458ce1dfb8d56c91ad38effb6974d371b6ad206e484e49ed7013c")
		s.Require().NoError(err)

		transfer := tx.Transfer{
			Source:      w.Address(),
			Destination: "DAG1ATvdAxGz4DNzPdrk6p8QD1CdSXNLvYypaaVQ",
			Amount:      tx.Datoshi(100000),
			Fee:         tx.Datoshi(10000),
			Parent: tx.Ref{
				Hash:    "0000000000000000000000000000000000000000000000000000000000000000",
				Ordinal: 0,
			},
			Salt: 8725724278030335, // MIN_SALT — matches the dag4.js vector
		}

		signed, err := w.Sign(transfer)
		s.Require().NoError(err)

		s.Require().Len(signed.Proofs, 1)
		s.Equal(
			"043a1d350d041e8291ce672386f80cabfc16716f5a54532e17519a66fe6f9fedd8717e327ff4be399a303a8de1056f4769750487a278b8f8fe4f7add55bd5b4d",
			signed.Proofs[0].ID,
		)
		s.Equal(
			"304502210081b8415843842e8811972b2b24127e37d80e05c754ed65261b6fb6cc854d9d6502204d87a0c7155d0d46a1b5480ba4bff8ef9f2ca3d750d5389e92e654a8395ab993",
			signed.Proofs[0].Signature,
		)
		s.Equal(transfer, signed.Value)
	})

	s.Run("auto-generates salt when zero", func() {
		w, err := FromPrivateKey("9bfe101efc5458ce1dfb8d56c91ad38effb6974d371b6ad206e484e49ed7013c")
		s.Require().NoError(err)

		transfer := tx.Transfer{
			Source:      w.Address(),
			Destination: "DAG1ATvdAxGz4DNzPdrk6p8QD1CdSXNLvYypaaVQ",
			Amount:      tx.Datoshi(100000),
			Fee:         tx.Datoshi(10000),
			Parent:      tx.Ref{Hash: "0000000000000000000000000000000000000000000000000000000000000000", Ordinal: 0},
		}

		signed, err := w.Sign(transfer)
		s.Require().NoError(err)
		s.NotZero(signed.Value.Salt, "Sign should populate zero-salt transfers")
	})
}
